### ISSUE TITLE
Null or Empty Set Checks

### ISSUE THREAD

**Issue by alanspires** [thepirat000/CachingFramework.Redis#10]
When passing in a empty collection to

[https://github.com/thepirat000/CachingFramework.Redis/blob/master/CachingFramework.Redis/RedisObjects/RedisSet.cs#L34](url)

an exception gets thrown stating "ERR wrong number of arguments for 'sadd' command". Can we add null and empty checks to relevant routines? I can create a pull request if you want.

**Comment by thepirat000** [comment]
You are absolutely welcome to create the pull request :)
