### ISSUE TITLE
GetKeysByPattern is slow when using hash

### ISSUE THREAD

**Issue by mrcode86** [thepirat000/CachingFramework.Redis#11]
I try to search for matching keys but when i use hashes its realy slow, 57 seconds to get a result.
I use this:
SetHashed("user:1:username, UserObject.AsDictionary());
And when i try to search for matching keys:
GetKeysByPattern("user:*:username") or GetKeysByPattern("user:1:username")  <-- 57 seconds. 

When i do the same in Redis Desktop Manager, i get the result directly.

When i store my data like, SetObject("user:1:username, UserObject) the GetKeysByPattern is fast.

How can i find keys when i use hash?

**Comment by thepirat000** [comment]
Hi

Note that the `GetKeysByPattern` internally calls the SE.Redis `server.Keys` for each server in the cluster. The command sent to the server can be [KEYS](http://redis.io/commands/keys) or [SCAN](http://redis.io/commands/scan) based on server version (see [this](http://stackoverflow.com/a/26440148/122195)).

My advice is to avoid using the `GetKeysByPattern` since it needs to iterate over the entire keyspace of all the servers. 

From Redis [KEYS](http://redis.io/commands/keys) command documentation:
> Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code.

Can you [MONITOR](http://redis.io/commands/MONITOR) your Redis database to check the command generated? (KEYS or SCAN).

**Comment by mrcode86** [comment]
Hi,

thanx for your answer.
When i monitor redis server on azure i can se this: "SCAN" "0" "MATCH" "user:*:username"
When i use a filter in, Redis Desktop manager, i get this: "HSCAN" "user:*:username" "0" "COUNT" "10000".

**Comment by thepirat000** [comment]
Ok. There is a huge difference between SCAN and HSCAN. Do you want to match fields over a given Hash? Or you want to match keys over the entire redis keyspace?

For the first option, the library currently does not provide a way to match fields of a hash with a pattern (I'll will work on adding this feature).

In the meantime, what you can do is to get the [StackExchange.Redis multiplexer](https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/PipelinesMultiplexers.md#multiplexing) and use the HashScan method.

For example:
```C#
var ctx = new Context();
var hashKey = "user:1";
ctx.Cache.SetHashed(hashKey, "Id", 1);
ctx.Cache.SetHashed(hashKey, "Name", "Federico");
ctx.Cache.SetHashed(hashKey, "Age", 37);
ctx.Cache.SetHashed(hashKey, "Birthdate", new DateTime(1979, 8, 17));

// Execute HSCAN (get all fields ending with an 'e'
var fields = ctx.GetConnectionMultiplexer().GetDatabase().HashScan("user:1", "*e", 10).ToList();
// Manually deserialize the values
var values = fields.Select(f => f.Name + " = " + ctx.GetSerializer().Deserialize<object>(f.Value));
```

**Comment by mrcode86** [comment]
Thanx for the information. My main problem is that i want to get the cache using the username or the userid. Sometimes i only know the userid so i need to search for the right key. Then i use, user:[USERID]:[USERNAME]. The most important part is the [USERNAME] so, maybe its better to only use, user:[USERNAME] or what is the best way?

**Comment by thepirat000** [comment]
Use the (unique) field that you have **most of the time** as the key, either the Id or the Username. 
You can have another hash to store the relation Name->Id

For example:
If you store the user data related to the Id:
```c#
ctx.Cache.SetHashed("user:12", new Dictionary<string, object>()
{
	{"UserData for Mary...", "..."} //...
});
ctx.Cache.SetHashed("user:34", new Dictionary<string, object>()
{
	{"UserData for John...", "..."} // ...
});
```

Have a hash with the relation username -> id:

```c#
context.Cache.SetHashed("username-id", "Mary", 12);
context.Cache.SetHashed("username-id", "John", 34);
```

Then you can get the user data by either id or name:
```c#
IDictionary<string, object> GetFromId(int userId)
{
	return context.Cache.GetHashedAll<object>("user:" + userId);
}

IDictionary<string, object> GetFromName(string userName)
{
	int userId = context.Cache.GetHashed<int>("usernames", userName);
	return context.Cache.GetHashedAll<object>("user:" + userId);
}
```

**Comment by thepirat000** [comment]
I've implemented the **HSCAN** with pattern match on method `ScanHashed` of the cache provider.
It is available from version 5.1.

An example [here](https://github.com/thepirat000/CachingFramework.Redis/blob/master/README.md#scan-fields-by-pattern)

Closing this.

**Comment by alanspires** [comment]
Impressed with the quick turnarounds on the issues fyi right on bro

**Comment by thepirat000** [comment]
Thanks :)

**Comment by mrcode86** [comment]
Thanx for your help. I think i will use user:[USERNAME].
Maybe i should create a new topic, but is there a function to increase a value, like this in a hash: HINCRBY user:david UnitFollowers -1

**Comment by attiqueahmed333** [comment]
Don't have exact key to get list from redis as i want to scan by roles.

{
   users: [
          {
                userid:1,
                username: abc,
                 userrole: admin
            },
{
                userid:1,
                username: abc,
                 userrole: admin
            }

           ]

}

var list = db.HashScan(key, "UserRole").ToArray()
