### ISSUE TITLE
Timeout during connection

### ISSUE THREAD

**Issue by HaythemJ** [thepirat000/CachingFramework.Redis#13]
Hi,

Redis is installed on windows server. Some times during connection to the redis server I am getting timeout. Below my configuration:

```
var redisHost = cacheConfig.host;
var redisPort = cacheConfig.port;
var redisPassword = cacheConfig.password;

 var redisConnectionString = redisHost + ":" + redisPort + ",password=" + redisPassword + ",connectRetry=5,connectTimeout=5,keepAlive=60, syncTimeout=10000";

var context = new Context(redisConnectionString);

this.unityContainer.RegisterInstance<IContext>(context);
```
Using the Redis Client redis-cli.exe it works perfectly but sometimes on my ASP.NET application am not able to connect using code above. I got Timeout Exception.

One more question: Once having the connection I am storing the context using DI UnityContainer. And later I am using this single instance reference in my Web API controllers: Is this a best practice or I should reconnect one more time for each connection?

Best Regards
H.JAIDI

**Comment by thepirat000** [comment]
Hi

It is OK to reuse the same context instance as you are doing.

About the timeout exception I doubt that it has something to do with the library itself.
Did you tried changing the connection timeout?

Check this [SE Redis Issue](https://github.com/StackExchange/StackExchange.Redis/issues/12) and this [Azure blog post](https://azure.microsoft.com/en-us/blog/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/)

**Comment by HaythemJ** [comment]
Thank you. Much appreciated.

for timeout it is ok.

For Singleton use, I afraid that connection did have a Time-To-Live. So after a while it want be a valid connection. Also for configuration change reason (host and port) I register the context as Type in the UnityContainer with TransientLifetimeManager so that I can instantiate a new context with current configuration.

**Comment by thepirat000** [comment]
The Caching.Framework's `Context` internally holds a reference to a StackExchange.Redis `ConnectionMultiplexer`. This multiplexer already takes care of the actual **connections**. The `Context` by itself does not have connections, so it's not affected by the time-to-live.
