### ISSUE TITLE
Projecting Requiring StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by jmarbutt** [thepirat000/CachingFramework.Redis#15]
@thepirat000  So I have a project that has a 3rd party that requires the StackExchange.Redis.StrongName which obviously causes a huge headache when trying to reference this nuget package. Any idea on how I can get around this?

**Comment by thepirat000** [comment]
Hi

Just added the strong name version for CachingFramework.Redis and CachingFramework.Redis.Json.

Please use the following packages:

https://www.nuget.org/packages/CachingFramework.Redis.StrongName/
and
https://www.nuget.org/packages/CachingFramework.Redis.Json.StrongName/

**Comment by thepirat000** [comment]
Closing this
