### ISSUE TITLE
Concurrent connections problem

### ISSUE THREAD

**Issue by mrcode86** [thepirat000/CachingFramework.Redis#16]
Hi,

I try to do a lot of  concurrent requests to the redis server but i get, "No connection is available to service this operation: HGETALL user:16"

This is what i try to do in my test project:
```
[TestMethod]
public void TestAsync()
{
     var CacheTasks = new List<Task>();
     for (var i = 0; i < 200; i++)
     {
          CacheTasks.Add(Task.Run(() =>
          {
                 Caching.Connection.GetConnection.GetHashedAll<object>($"user:16");
           }));
     }
     Task.WaitAll(CacheTasks.ToArray());
}
```

In my Connection class:

```
public static class Connection
{
        private static readonly CachingFramework.Redis.Json.Context Context =  new CachingFramework.Redis.Json.Context("XXXXX.redis.cache.windows.net, connectRetry=10, abortConnect=false, allowAdmin=true, ssl=true, password=XXXXXX");
        public static ICacheProvider GetConnection => Context.Cache;
        public static IDatabase StackConnection => Context.GetConnectionMultiplexer().GetDatabase(0);
}
```
I use Redis on Azure (C2 basic)

I want to se how fast it is to do 200 gets :)

**Comment by thepirat000** [comment]
I think this is not related to this library nor the StackExchange.Redis library.
This is inherent to Redis itself.

Please see this [SE.Redis issue](https://github.com/StackExchange/StackExchange.Redis/issues/12)
and a nice explanation [here](http://stackoverflow.com/questions/22930856/stackexchange-redis-timeout-and-no-connection-is-available-to-service-this-oper).
Also there is another issue mentioning the same thing:
https://github.com/thepirat000/CachingFramework.Redis/issues/13

And [this one](http://stackoverflow.com/questions/25416562/stackexchange-redis-with-azure-redis-is-unusably-slow-or-throws-timeout-errors) specifically for Azure problems

Try changing the Redis SAVE configuration:
http://redis.io/commands/config-set
