### ISSUE TITLE
Question. Is it possible to apply tags to members of sets?

### ISSUE THREAD

**Issue by alanspires** [thepirat000/CachingFramework.Redis#17]
Not sure if this is possible, would be very handy.

**Comment by thepirat000** [comment]
Very interesting idea!

The problem I foresee with tags pointing to set members is that the tag mechanism will need to store the member itself (a duplicated member value on the TAG sets).

But will think about this a little more.

**Comment by alanspires** [comment]
Would appreciate anything you could do. Would make mass deletes across geo, sorted indexes a piece of cake

**Comment by thepirat000** [comment]
coming soon...

**Comment by alanspires** [comment]
🙌

**Comment by thepirat000** [comment]
ok I think this is done.

From version 6.2, you should be able to relate tags to keys, hash fields, set members, sorted set members and geospatial index members.

Please see the updated documentation:
https://github.com/thepirat000/CachingFramework.Redis#tagging-mechanism
https://github.com/thepirat000/CachingFramework.Redis/blob/master/COLLECTIONS.md


Thanks for the great suggestion.

Hope it helps
