### ISSUE TITLE
Strings stored in sorted sets

### ISSUE THREAD

**Issue by alanspires** [thepirat000/CachingFramework.Redis#18]
When storing strings (int indexes) into a sorted set they are saved in a weird format.
"\"12345"\\

So when I try to remove a member using 

GetConnectionMultiplexer().GetDatabase().SortedSetRemoveAsync(key,"12345") 

It doesn't get removed from the set.

**Comment by thepirat000** [comment]
Hi 

What version of the library are you using?
What serializer do you use?

**Comment by alanspires** [comment]
Using 5.1.0 as I haven't implemented .netstandard yet. Using the JSON serializer.

**Comment by thepirat000** [comment]
Try with:

```c#
var value = JsonConvert.SerializeObject("12345");
GetConnectionMultiplexer().GetDatabase().SortedSetRemoveAsync(key, value)
```

Or just use the `RedisSortedSet` object from CachingFramework.Redis.
```c#
var sset = context.Collections.GetRedisSortedSet<string>(key);
sset.Remove("12345");
```

**Comment by alanspires** [comment]
Ya that makes sense lol, spaced out, Fridays....

**Comment by thepirat000** [comment]
You should be able to use the latest version even targeting the full .NET framework.

Let me know if you have any problems to restore the latest version?

**Comment by alanspires** [comment]
I need to read up on that, been lazy. All the dependencies that get added freak me out lol
