### ISSUE TITLE
Major issue with CachingFramework.Redis above than 5.1

### ISSUE THREAD

**Issue by vdevappa** [thepirat000/CachingFramework.Redis#19]
If you reference this in a project, it adds references to .NET core libaries. If the library is then referenced within a web role, it clashes with the .NET 4.6.2 dlls like System.IO.Compression and System.Net.Http eventually causing the web role to fail either on the cloud OR on the local azure emulator because it cannot run normal .NET 4.6.2 ASP.NET application using the System.IO.Compression.dll from .NET Core.

Took me a while to find this out. Please provide separate versions for older .NET Framework vs .NET Core or provide a way to help me use the latest version without ending up with this issue.

**Comment by thepirat000** [comment]
Oh man... Sorry about that!

The library had the NET Standard dependency also for the full framework and I never noticed that.

Will fix this ASAP

**Comment by thepirat000** [comment]
BIG mistake from my part...

This should be fixed now on version v7.0.0

Please let me know if you still have problems, otherwise we can close this

**Comment by vdevappa** [comment]
I will try this on Monday and see what happens. Thanks!

On Nov 18, 2016, at 8:41 PM, Federico Daniel Colombo <notifications@github.com<mailto:notifications@github.com>> wrote:


BIG mistake from my part...

This should be fixed now on version v7.0.0

Please let me know if you still have problems, otherwise we can close this

-

**Comment by vdevappa** [comment]
This works now. Thanks!
