### ISSUE TITLE
FindIndex?

### ISSUE THREAD

**Issue by du8die** [thepirat000/CachingFramework.Redis#22]
Hello,

When using iRedisList, there is no FindIndex method. There are also no (apparent) ways to replace an object in a list.

Use case:
I have an object that contains an array. When an array item is added, it's seen as a new object in CF.Redis - and "doubled" in the cache. Is there a way to update the first object? Or - is there a way to find it by a field name? (Since the objects have been serialized already)?

Thanks,

**Comment by thepirat000** [comment]
There is no `FindIndex`, but there is an `IndexOf` method that is part of the `IList<T>` interface.

```c#
var ctx = new Context();
var l = ctx.Collections.GetRedisList("Key");
int i = l.IndexOf("item");
```

Also you should be able to replace an element by using the indexed property setter:

```c#
var ctx = new Context();
var l = ctx.Collections.GetRedisList("Key");
l[2] = "new item";
```

**Comment by du8die** [comment]
Sure - that works great if it's a string. However, if it's an object, this doesn't work.

```
public class demo
{
	public string id { get; set; }
	public list<string> prop { get; set; }
}
```

The object in cache is:
```
{
  id:"123",
  prop: [ "abc","def"]
}
```

I'm trying to find replace it with 
```
{
  id:"123",
  prop: ["abc","def","ghi"]
}
```

Suggestions?

**Comment by thepirat000** [comment]
The value stored on the redis list will be the serialized value of the object to inserted on the list. so for the `IndexOf` method, the object `{ id:"123", prop: [ "abc","def"] }` is no the same than `{ id:"123", prop: [ "abc","def", "ghi"] }` so it will not find it
