### ISSUE TITLE
Having dependency issue with > Stackexchange.Redis 1.1.608

### ISSUE THREAD

**Issue by lilmidnit** [thepirat000/CachingFramework.Redis#23]
I have the 7.0.1 of CachingFramework.Redis installed and when I update my solution to use StackExchange.Redis to anything greater than 1.1.608 (1.2.1) and try to new Context() I get an error saying 1.1.608 is not found. I have searched my solution to ensure I have nothing defining a version requirement on 1.1.608 and I am at a loss. Any idea why this is occuring? It only effects CachingFramework.Redis and not other libraries that also depend on StackExchange.Redis

**Comment by lilmidnit** [comment]
I forgot to mention I am using .NET 4.6.2

**Comment by thepirat000** [comment]
Please try again with version >= 7.1.1

**Comment by thepirat000** [comment]
Feel free to reopen the issue if you are still having problems with latest version
