### ISSUE TITLE
Missing FetchObject<T>(key) overload

### ISSUE THREAD

**Issue by jovball** [thepirat000/CachingFramework.Redis#28]
The examples show this but none of the overloads support this. All of them are using the CacheAside pattern.

**Comment by thepirat000** [comment]
What does `FetchObject<T>(key)` should do?
Return the object of type `T` at key `key`?
If so, then the method you're looking for is not `FetchObject`<T>  but `GetObject<T>;`

For example:

```
User user = context.Cache.GetObject<User>(redisKey);
```
