### ISSUE TITLE
TTL for GeoAdd

### ISSUE THREAD

**Issue by nkovacic** [thepirat000/CachingFramework.Redis#29]
Will TTL (Time to Live) be added for GeoProvider?
Currently this options does not exist on the API.
Btw great framework for redis on ASP.NET 👍

**Comment by thepirat000** [comment]
Thanks.

Actually there is no way to set a time-to-live to **individual** items in a Redis hash or geohash. You can only set a TTL to an entire redis key (i.e. the whole geohash).

The current technique implemented for _SetHashed_ methods, is to maintain the longest time-to-live, so for example if you add the following hash values:

```c#
cache.SetHashed("k", "f1", 1, TimeSpan.FromMinutes(10));
cache.SetHashed("k", "f2", 2, TimeSpan.FromMinutes(30));
```

The entire hash at key "k" will be invalidated after 30 minutes.

If you want something similar to this but for geohashes, I can work on that.

**Comment by thepirat000** [comment]
I'm closing this because this can be accomplished by using `KeyTimeToLive(string, TimeSpan)`, to set a TTL to an entire key.

Feel free to re-open if you are still having issues
