### ISSUE TITLE
Best practices for ConnectionMultiplexer not being followed?

### ISSUE THREAD

**Issue by hesperanca** [thepirat000/CachingFramework.Redis#30]
Gents,

According to [this Microsoft Article](https://docs.microsoft.com/en-us/azure/redis-cache/cache-dotnet-how-to-use-azure-redis-cache)  the ConnectionMultiplexer should be reused. They recommend using a Lazy static variable to store it (see connect to cache section). 

There is also a blog post talking about this [here](https://gavinb.net/2015/07/11/dont-get-burned-by-redis-connectionmultiplexer-a-sample-wrapper/)

I've noticed that, on this implementation, a new instance of the ConnectionMultiplexer is created per Context object. Is this correct? Shouldn't we be storing  the  ConnectionMultiplexer inside of a Lazy static property on the RedisProviderContext?

Cheers,
Hugo

**Comment by thepirat000** [comment]
Actually, since the `Context` class is wrapping an instance of the `ConnectionMultiplexer`, same rules applies to the `Context` class: it should be shared and reused between callers.

I've added a note for this on the [documentation](https://github.com/thepirat000/CachingFramework.Redis#context).

**Comment by hesperanca** [comment]
Yes that will work as well.

Thanks for all the great work with the framework by the way.

Cheers,
Hugo
