### ISSUE TITLE
Assembly to be signed

### ISSUE THREAD

**Issue by Pandiarajan** [thepirat000/CachingFramework.Redis#31]
Hi,
Unable to reference this wonderful project when the existing project is signed.

Thanks,
Pandiarajan.

**Comment by thepirat000** [comment]
You must use the packages ending with StrongName: i.e.  CachingFramework.Redis.StrongName

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Pandiarajan** [comment]
Thanks, that works fine.
