### ISSUE TITLE
Using Jsonserializer with Asp.net mvc website

### ISSUE THREAD

**Issue by vikas3045** [thepirat000/CachingFramework.Redis#32]
Hi, I am trying to use Jsonserializer instead of default BinarySerializer in Asp.net MVC based website.

1. Is there any benefit (performance or something else) of using a JsonSerializer over BinarySerializer or vice versa?

2. Also, I was looking for some cache lookup method like
T FetchHashed<T>(string key, string field, Func<T> func, TimeSpan? expiry = null);
for SortedSet. Please suggest if any method with similar functionality already exists or I should write one?

By the way, thanks for the amazing work on this library!

**Comment by thepirat000** [comment]
Hi, sorry for the delay.

1. BinarySerializer Pros: Data is compressed. Full inheritance support. BinarySerializer Cons: Not human readable, no NET Core support, must be deserialized with the same assembly/framework version.
JsonSerializer Pros: Anyone can read and parse. Cons: Size.

For 2. I don't see how to implement such a function for a sortedset. Many members could have the same score, how would the method determine if the value is already present or not?
