### ISSUE TITLE
Removing Hashed value from set does not remove Tag

### ISSUE THREAD

**Issue by Fenglei-Pan** [thepirat000/CachingFramework.Redis#34]
I realize an issue when resuse same key and field in set with tags.
After I remove hashed values, tag for this value is still exist.  If I add the same key and field value to set again, previous tag will apply to the new value.
ex: 
`
obj1.Status="Open";
context.Cache.SetHashed("Key1", "Field1", obj1, new[] {obj1.Status});   
context.Cache.RemoveHashed("Key1", "Field1");
obj1.Status="Close"
context.Cache.SetHashed("Key1", "Field1", obj1, new[]{obj1.Status});   
var obj = context.Cache.GetObjectsByTag<string>("Open").FirstOrDefault(); 
//expect obj is null, but returned obj1.
`

**Comment by thepirat000** [comment]
That's a side effect of the way the tags are handled.

Tag relations are not implicitly removed when you remove an element by id, if you want a key-tag relation to be removed explicitly, you can call the `RemoveTagsFromHashField()` method.

Tag relations are removed on the following cases:
- When `InvalidateKeysByTag()` is called.
- When obtaining keys related to the tags with `GetKeysByTag()` with `cleanUp` parameter set to `true`.
- Explicitly removing a tag relation with `RemoveTagsFrom___()` methods.

**Comment by Fenglei-Pan** [comment]
Thanks for your reply. 
To call `RemoveTagsFromHashField()` method, I need to pass in all existing tags, should I create another redis set to remember all tags for HashField?

Code for SetHashed:
`
var tags=new[] {"tag1","tag2","tag3","tag4"};
context.Cache.SetHashed("Key1", "Field1", obj1, tags); 
foreach(var tag in tags)
      context.Cache.AddToSet("Key1:Field1", tag);
`
Code for RemoveHashed:
`
var currentTags = context.Collections.GetRedisSet<string>("Key1:Field1");
context.Cache.RemoveHashed("Key1", "Field1"); 
context.Cache.RemoveTagsFromHashField("Key1", "Field1", currentTags);

`

**Comment by thepirat000** [comment]
yes you can do that.
You can use the `GetRedisSet` for adding multiple values to the set:

```
var x = context.Collections.GetRedisSet<string>("Key1:Field1");
x.AddRange(tags);
```

But I wonder why you need to change the tags. The main purpose of tagging is for cache invalidation.

Regards

**Comment by Fenglei-Pan** [comment]
I use tags to filter objects. Otherwise I need to deserialize all objects and loop through each object to filter.
Is there any better ways to filter cached objects in redis?

**Comment by thepirat000** [comment]
Yes, that fits perfectly, you can get the keys/fields related to a tag or invalidate them all at once. 

But it looks like you also need to _change_ the tags for a key, or _know_ the tags related to a given key, and that's not supported with the current implementation, since the tagging mechanism is implemented as Redis Sets that relates TAGs to KEYs, but not otherwise.

**Comment by Fenglei-Pan** [comment]
Thanks, I can use previous recommended code to manage tags in another Redis Set for Keys to Tags relation. And it is working fine now.
