### ISSUE TITLE
not able to set TTL of IRedisSet

### ISSUE THREAD

**Issue by PrachiChoudhary** [thepirat000/CachingFramework.Redis#35]
Hi

I am not able to set TTL of IredisSet, it is always null. Check the below code. Let me know if there is something wrong. I have also tried using property TimeToLive as shown in comment inside if.

public void AddToSet<T>(string key, T value)
        {
            bool keyexistedPreviously = _context.Cache.KeyExists(key);
            
            IRedisSet<T> set = _context.Collections.GetRedisSet<T>(key);
            TimeSpan? previousTTL = set.TimeToLive;
            if (!keyexistedPreviously)
            {
                //set.TimeToLive = TimeSpan.FromHours(expireTimeinHour); 
                _context.Cache.KeyTimeToLive(key, TimeSpan.FromHours(expireTimeinHour));
            }
            TimeSpan? ttl = set.TimeToLive;
            set.Add(value);
            TimeSpan? afterTTL = set.TimeToLive;
        }

**Comment by thepirat000** [comment]
The problem is that the set is not created on Redis until you add the first element to it, so you cannot set the time to live of a key that doesn't exists. (In the same way, Redis deletes the key when the last element of a set is removed).

So I think if you move up the `set.Add`, it should work.

```c#
...
IRedisSet<T> set = _context.Collections.GetRedisSet<T>(key);
set.Add(value);
TimeSpan? previousTTL = set.TimeToLive;
...
```
