### ISSUE TITLE
Exception When context.Cache.GetObjectsByTag

### ISSUE THREAD

**Issue by zhusheping** [thepirat000/CachingFramework.Redis#36]
I'v two class here. When there instances added into set, the same Tag "red" added!
And I wan't to get instances of a certain class respectively,exception throwed!

[Serializable]
    public class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
    }
    [Serializable]
    public class Student
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
in main:
           `Context context = new Context("localhost:6379", new JsonSerializer());         
            IRedisSet<User> userset = context.Collections.GetRedisSet<User>("user:set");
            userset.Add(new User() { Id = 1 },new[] { "red"});
            IRedisSet<Student> stuset = context.Collections.GetRedisSet<Student>("stu:set");
            stuset.Add(new Student() { Id = "x9527" }, new[] { "red" });
            
            IEnumerable<User> users = context.Cache.GetObjectsByTag<User>("red", "green");
            foreach (var item in users)
            {
                Console.WriteLine(item.Id);
            }
            IEnumerable<Student> stus = context.Cache.GetObjectsByTag<Student>("red", "green");
            foreach (var item in stus)
            {
                Console.WriteLine(item.Id + item.Name);
            }
`

Here throwed a exception at foreach (var item in users):Additional information: Could not convert string to integer: x9527. Path 'Id', line 1, position 13.

**Comment by thepirat000** [comment]
The problem is that you cannot selectively retrieve tagged objects _by type_. The framework will always retrieve all the values related to the tag, and since you are using the default serialization method that does not includes the type in the serialized value, the framework will fail when trying to deserialize a `Student` value as a `User`.

I think the best option to make it work is to Store the type on the serialization and retrieve the `objects` of the correct type:

```C#
var context = new Context("localhost:6379", new CachingFramework.Redis.Serializers.JsonSerializer(new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All }));

IEnumerable<object> all = context.Cache.GetObjectsByTag<object>("red", "green");
foreach(var obj in all)
{
    if (obj is User)
    {
        var user = obj as User; //...
    }
    else if (obj is Student)
    {
        var student = obj as Student; //...
    }
}
```

Important part is `TypeNameHandling = TypeNameHandling.All`

**Comment by zhusheping** [comment]
Yes it works.but i's not very elegant.I's a generic method.
I think `context.Cache.GetTypedObjectsByTag`  is  better.
btw,`
Context context = new Context("localhost:6379",
    new CachingFramework.Redis.Serializers.JsonSerializer(new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.Auto }));
`
is not worked also!
and the default BinarySerializer has none constructor with a SerializerSettings param.
It looks that retrieve the object's type is the only way.
Thanks a lot.

**Comment by zhusheping** [comment]
if `Context context = new Context("localhost:6379", new CachingFramework.Redis.Serializers.JsonSerializer(new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.Auto }));`


```
IEnumerable<object> all = context.Cache.GetObjectsByTag<object>("red", "green");
foreach(var obj in all)
{
   //obj's is always Newtonsoft.Json.Linq.JTokenType
    if (obj is User)
    {
        var user = obj as User; //...
    }
    else if (obj is Student)
    {
        var student = obj as Student; //...
    }
}
```

**Comment by thepirat000** [comment]
Using `TypeNameHandling.Auto` has the same effect than the default JSON serialization: the value on Redis will not include the type. The value content on redis will be like `{"Id":"x9527","Name":null}` and `{"Id":1,"UserName":null}`. There is no way to implicitly infer the type, so the deserialization returns a `JObject` you can then [convert to an object](https://stackoverflow.com/a/12208692/122195).

Instead if you set name handling to `.All`, the type will be explictly included on the content, for example: `{"$type":"YourApp.User, YourApp","Id":1,"UserName":null}`, so the JSON deserializer will deserialize to the correct type.

With BinarySerializer you don't need to specify a custom setting since it will always include the type and it will be always able to deserialize to the correct type. So my first answer also applies using the  `BinarySerializer`

**Comment by zhusheping** [comment]
In fact,i'm using the default serialization at first.There has none expecting results,so i wrote this issue.
the whole code:

```
[Serializable]
    public class User
    {
        public int Id { get; set; }
        public string UserName { get; set; }
    }
    [Serializable]
    public class Student
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
    class Program
    {
        static void Main(string[] args)
        {
            Context context = new Context();
            //Context context = new Context("localhost:6379",new BinarySerializer()); // also not worked!
            User u = new User() { Id = 1 };
            Student s = new Student() { Id = "x9527" };
            context.Cache.AddToSet("user", u, new[] { "red" });
            context.Cache.AddToSet("stu", s, new[] { "red" });
            foreach (var item in context.Cache.GetObjectsByTag<User>("red"))
            {
                Console.WriteLine(item.Id);
            }
            Console.ReadLine();
        }
    }
```
The exception: Unable to convert objects of type "RedisCacheTest.Student" to type "RedisCacheTest.User"
It's apparent that it will not be always able to deserialize to the correct type.

**Comment by thepirat000** [comment]
Maybe I was not clear on my responses, but the exception you are getting is expected.

[`GetObjectsByTag<T>()`](https://github.com/thepirat000/CachingFramework.Redis#get-objects-by-tag) method assumes **all** the keys related to the tag can be deserialized to the type `T`. 

This method retrieves all the keys related to the given tags, and one by one it deserializes the values to the given type `T`. Meaning that whatever method you use to serialize (built-in JSON, built-in Binary or a [custom serialization method](https://github.com/thepirat000/CachingFramework.Redis#serialization)) it must be able to deserialize all the values related to the tag, to the type `T`.

Also this method is not meant to filter objects by type or by anything, it will just retrieve all the keys related to a given tag and deserialize its values to the given type by [calling the configured serialization method](https://github.com/thepirat000/CachingFramework.Redis/blob/master/src/CachingFramework.Redis/Providers/RedisCacheProvider.cs#L743).

So I suggested you different options to use `GetObjectsByTag<T>()` to get objects of different types:

1. Include the type on the JSON, with `TypeNameHandling.All` setting and request all the values as `<object>` so you'll get the objects as its original type.
2. Use the BinarySerializer in the same way.
3. Leave the JSON setting as default (not including the type on the redis value) and deserialize to the generic `JObject` that you can then convert to an object by calling `JObject.ToObject`

You could also supply your custom serialization method that handle your scenario.

You could also use [`GetKeysByTag()`](https://github.com/thepirat000/CachingFramework.Redis#get-keys-by-tag) method that only retrieves the **keys** related to the tag, so you can guess the type depending on the key.

That being said, I still see no defect here.
