### ISSUE TITLE
Get callback when item is removed from the cache?

### ISSUE THREAD

**Issue by RahmanM** [thepirat000/CachingFramework.Redis#39]
Hi there,

I can't see if there is a way to get callback when item is removed from the cache? This will be a very nice feature if can be done easily?

ta

**Comment by thepirat000** [comment]
do you mean when it is removed explicitly from the cache? or also when they are expired because of TTL? The latter is not possible

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thepirat000** [comment]
have you seen the keyspace notifocation api? https://github.com/thepirat000/CachingFramework.Redis/blob/master/README.md#keyspace-notifications-api

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RahmanM** [comment]
Ah thanks,

That is what I was exactly looking for, not sure why I didn't see this section of documentation in the first place. I have already enabled notify-keyspace-events but possibly using it the wrong way. I give it another try and let you know.

TA

**Comment by thepirat000** [comment]
you must enable keyspace notification in the redis server(s). Check
https://redis.io/topics/notifications#configuration
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RahmanM** [comment]
Thanks, this perfectly works.
