### ISSUE TITLE
SlidingExpiration? 

### ISSUE THREAD

**Issue by RahmanM** [thepirat000/CachingFramework.Redis#40]
Hi
I don't seem to be able to find how to set sliding expiration on cached item e.g expire cache if cache is not accessed within specified ttl time?

Any tricks? 

Ta

**Comment by thepirat000** [comment]
There no built-in command on redis to do that, check [this](https://stackoverflow.com/questions/20280316/absolute-and-sliding-caching-in-redis).

To implement a sliding expiration you need to reset the TTL value after each GET command.
For example:

```
public async Task<T> Get<T>(string key, TimeSpan slidingExpiration)
{
    var ctx = new Context();
    var value = await ctx.Cache.GetObjectAsync<T>(key);
    await ctx.Cache.KeyTimeToLiveAsync(key, slidingExpiration);
    return value;
}
```

**Comment by RahmanM** [comment]
Ok, but you need to keep track of items in the cache as which one are really sliding expiration. I was thinking to tag them (though not possible as Get functions doesn't return tags)  or maybe a wrapper like CacheItem<T> with extra properties incl ExpirationDateTime that actually wraps the thing to be cached?

Ta

**Comment by thepirat000** [comment]
I think I'm missing your point. 

Can you elaborate including the redis commands to be executed?

**Comment by RahmanM** [comment]
I think the clients or the user of the cache should not pass the TimeSpan slidingExpiration as most of the time they don't know if an item in the cache is added with sliding expiration or not. E.g we are adding items  in data entry screens and then 3rd party API is querying it etc. 

I am thinking for me issue something like:

```
public add =>

public void Add(string key, TValue item, TimeSpan slidingExpiration)
        {
            Add(key, new CacheItem<TValue>(item, slidingExpiration));
        }

privately add=>

 private void Add(string key, CacheItem<TValue> cacheItem)
        {
            if (string.IsNullOrWhiteSpace(key))
                throw new ArgumentNullException(nameof(key));

            if (cacheItem == null)
                throw new ArgumentNullException(nameof(cacheItem));

            _Cache.SetObject(key, cacheItem);

            if (cacheItem.SlidingExpiration > TimeSpan.Zero)
            {
                _Cache.KeyTimeToLive(key, cacheItem.SlidingExpiration);
            }

            if (cacheItem.AbsoluteExpiration > DateTime.MinValue)
            {
                _Cache.KeyExpire(key, cacheItem.AbsoluteExpiration);
            }
        }

and then Public Get => :

 public TValue Get(string key)
        {
            var cacheItem = _Cache.GetObject<CacheItem<TValue>>(key);

            if(cacheItem.SlidingExpiration != TimeSpan.Zero)
            {
                _Cache.KeyTimeToLive(key, cacheItem.SlidingExpiration);
            }

            return cacheItem.Item;
        }


public class CacheItem<TValue>
    {
        public CacheItem()
        {
            // ONLY to be used by run time serialisation.
        }

        public CacheItem(TValue item)
        {
            Item = item;
        }

        public CacheItem(TValue item, TimeSpan slidingExpiration)
        {
            SlidingExpiration = slidingExpiration;
            Item = item;
        }

        public CacheItem(TValue item, DateTime absoluteExpiration)
        {
            Item = item;
            AbsoluteExpiration = absoluteExpiration;
        }

        public TValue Item { get; set; }
        public TimeSpan SlidingExpiration { get; set; }
        public DateTime AbsoluteExpiration { get; set; }
    }

```

So the clients use it without any thinking this wrapper will reset the expiration if exist.

Thx

**Comment by thepirat000** [comment]
That should work fine. I'm closing this because I think this should not be included on the library, it's just a wrapper around the GET/EXPIRE pattern.

Feel free to re-open and/or create a PR if you have arguments to include this on the library.
