### ISSUE TITLE
Feature request: accept additional tags when using FetchHashed and tagsBuilder

### ISSUE THREAD

**Issue by mkontula** [thepirat000/CachingFramework.Redis#41]
FetchHashed has an overload which accepts Func<T,string[]> to build tags when miss has occured and data has been retrieved from Func<T>. 

It would be neat if one could supply addiotional string[] tags in the FetchHashed call. This would result in tag cloud constructed from T and additional array of tags supplied from the call site.

**Comment by thepirat000** [comment]
I don't get what you're asking for.
The cache provider has overloads to supply the tags as an array of strings, or as a function of the cached object value.

Can you provide come code or pseudo-code of what are you expecting?

**Comment by mkontula** [comment]
https://github.com/thepirat000/CachingFramework.Redis/blob/master/src/CachingFramework.Redis/Providers/RedisCacheProvider.cs#L69 Here tags are constructed by invoking the supplied tagsBuilder func. The func can only operate on the value of the Func providing T. I have a use case where tags should be constructed with tagsbuilder func _in addition_ to few extra tags witch are not related or constructable  from the value of T. 

New signature of the method could be FetchObjectAsync<T>(string key, Func<Task<T>> func, Func<T, string[]> tagsBuilder, string[] additionalTags, TimeSpan? expiry = null) and you only need to merge the two arrays before calling SetHashed. This way, one could still benefit from the Fetch-mechanism and avoid writing it again in a separate wrapper. Of course I could write one but since the hit-or-miss mechanism is already in place, it would be much more convenient to use it rather than writing a copy-paste version with little tweak.

**Comment by thepirat000** [comment]
> I have a use case where tags should be constructed with tagsbuilder func in addition to few extra tags witch are not related or constructable from the value of T

Why not to use the Func<T, string[]> just ignoring the T? like this? 

```
Cache.FetchHashedAsync<User>("users", "user:1", u => GetUserFromDb(), u =>
{
  var tags = new List<string>();
  tags.AddRange(GetTagsForUser(u));
  tags.AddRange(GetExtraTags());
  return tags;
});
```

**Comment by mkontula** [comment]
Indeed. Was too focused on thinking just about T. Thanks!
