### ISSUE TITLE
Is Cachingframework.Redis  is not compatible with .net core v2.0?

### ISSUE THREAD

**Issue by PrachiChoudhary** [thepirat000/CachingFramework.Redis#42]
While referring Cachingframework.Redis in lambda function getting following error. Please suggest whether it is not compatible. Do I need to chose any other version or any other library?

... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : warning NU1701: Package 'CachingFramework.Redis 5.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605: Detected package downgrade: System.IO.FileSystem from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.IO.FileSystem (>= 4.3.0) 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.IO.FileSystem (>= 4.0.1)
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version. 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0) 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Net.NameResolution (>= 4.0.0)
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605: Detected package downgrade: System.Net.Primitives from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Net.Primitives (>= 4.3.0) 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Net.Sockets 4.1.0 -> System.Net.Primitives (>= 4.0.11)
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605: Detected package downgrade: System.Threading.ThreadPool from 4.3.0 to 4.0.10. Reference the package directly from the project to select a different version. 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Net.Sockets 4.1.0 -> runtime.unix.System.Net.Sockets 4.3.0 -> System.Threading.ThreadPool (>= 4.3.0) 
... publish: D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj : error NU1605:  AWSLambda1 -> CachingFramework.Redis 5.1.0 -> StackExchange.Redis 1.1.608 -> System.Threading.ThreadPool (>= 4.0.10)
... publish:   Restore failed in 575.54 ms for D:\Dev\KinesisConsumer\data-in-trans\AWSLambda1\AWSLambda1.csproj.

**Comment by thepirat000** [comment]
Looks like a problem with your references, the package is compatible with netstandard 1.5, so it is also with 2.0.

Can you share your csproj content?

**Comment by thepirat000** [comment]
oh.. wait, you are restoring an old version CachingFramework.Redis (5.1.0), that one is not compatible with NetStandard. Upgrade to the latest version of the library: https://www.nuget.org/packages/CachingFramework.Redis/7.5.0

**Comment by PrachiChoudhary** [comment]
Hi it seems that it is not working with CachingFramework.Redis 7.5.0 also. We got same type of error. We are using Visual Studio 2017, can this be the issue? Please guide us

**Comment by thepirat000** [comment]
Can you provide, at least, the code that is failing and the error you're getting with 7.5.0?

**Comment by thepirat000** [comment]
oh.. I see... I think the problem is that AWS publishing command is treating the NU1605 warning as an error. But that warning seems to be triggered by the `StackExchange.Redis` library references. 

Can you try adding the following to your csproj?

```
<PropertyGroup>
    <NoWarn>NU1605</NoWarn>
</PropertyGroup>
```

**Comment by thepirat000** [comment]
I've published a new version of the library with explicit net standard 2 targeting, and updated the StackExchange.Redis library reference to the latest.

Please re-test with the new version 8.0.0

**Comment by PrachiChoudhary** [comment]
Thanks a lot. It worked with new version 8.0.0.

**Comment by Mohsinahabeeba** [comment]
hello sir, please hellp I am getting the following  message when trying to in stall through nuget
{Could not install package 'CachingFramework.Redis 10.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.}

**Comment by Mohsinahabeeba** [comment]
Is there any other solution ?  can restoring the previous version of this library can work? please help i'm in trouble

**Comment by Mohsinahabeeba** [comment]
thanks, changing the .Net framework worked for me :+1:

**Comment by Mohsinahabeeba** [comment]
thanks, changing the .Net framework version to 4.6.1 worked for me :+1:
