### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by nkovacic** [thepirat000/CachingFramework.Redis#43]
Is there anyway we could use this connection pool nuget for redis? Azure is throwing timeouts and suggesting to add it.
https://github.com/uliian/StackExchange.Redis.Pool

**Comment by thepirat000** [comment]
Hi, thanks for your suggestion.

I have added some overloads to the `RedisContext` class so you can inject your own `IRedisConnectionMultiplexer`, like the pooled connection you mentioned.

Please take a look at the unit test [here](https://github.com/thepirat000/CachingFramework.Redis/blob/master/test/CachingFramework.Redis.UnitTest/UnitTestConnectionMultiplexer.cs#L18).

For example:
```C#
var myMultiplexer = new PooledConnectionMultiplexer("localhost:6379");
var ctx = new CachingFramework.Redis.RedisContext(myMultiplexer);
//...
```

Note that the `Context` class is being renamed to `RedisContext`.

Please re-test with the latest version 8.1.0 and feel free to re-open this issue if you're still having problems.
