### ISSUE TITLE
GetRangeByScore() yields no result

### ISSUE THREAD

**Issue by PrachiChoudhary** [thepirat000/CachingFramework.Redis#44]
Is GetRangeByScore() is different from redis command ZRANGEBYSCORE? I am accessing same redis set with same score the redis command gives the result but GetRangeByScore() does not.
ZRANGEBYSCORE DEV|LatestData 1527572668036 +inf WITHSCORES // gives the list
But the following code yields empty enumeration

IRedisSortedSet<T> set = _context.Collections.GetRedisSortedSet<T>(key);
                    if (set.Count > 0)
                    {
                        IEnumerable<SortedMember<T>>  values =set.GetRangeByScore(1527572668036, double.PositiveInfinity);
                   }

Can you please help?

**Comment by thepirat000** [comment]
I have validated your exact call and the command executed was exactly:

`"ZRANGEBYSCORE" "key" "1527572668036" "+inf" "WITHSCORES"`

assuming key = "key"

Also tried with this code:
```
var key = "temp-key";
var context = new RedisContext("localhost:6379", new CachingFramework.Redis.Serializers.JsonSerializer());
var set = context.Collections.GetRedisSortedSet<string>(key);
set.Clear();
set.Add(1527572668037, "hi");
var values = set.GetRangeByScore(1527572668036, double.PositiveInfinity).ToArray();

values.Dump();
```

And I can confirm these were the commands executed:

```
DEL temp-key
ZADD temp-key 1527572668037 "hi"
ZRANGEBYSCORE temp-key 1527572668036 +inf WITHSCORES
```

And the last command returned:

> 1) "hi"
> 2) "1527572668037"

So I think you have a different problem here.

Use the [MONITOR](https://redis.io/commands/monitor) command on a redis-cli instance, to trace the commands being executed.

Feel free to re-open if you're still having issues
