### ISSUE TITLE
GetRangeByScore() with tags

### ISSUE THREAD

**Issue by PrachiChoudhary** [thepirat000/CachingFramework.Redis#45]
Hi

I am having a scenario where elements of my sorted set are tagged and I want to retrieve elements of sorted set after a particular score and a given tag. I found that there is a method called GetRangeByScore() which will will give elements after a particular score. And also there is method called GetObjectsByTag() to retrieve elements with given tag. But is there any method available for combination of two - retrieve elements after a particular score with a given tag.

**Comment by thepirat000** [comment]
There is no built-in mechanism to accomplish that in just one call.

The most performant solution will really depend on your data structure and access patterns.

One way could be using some methods that I've added on the latest version 8.2.0: `IsSetMemberInTag` / `GetMembersByTag`

I can think on two implementations:

```c#
// 1. Get range by score and filter one by one calling IsSetMemberInTag that is O(1)
var filtered = sortedSet.GetRangeByScore(double.NegativeInfinity, 500)
	.Where(m => ctx.Cache.IsSetMemberInTag("sorted set key", m.Value, "TAG 1"));
```

```c#
// 2. Get all the members for a tag and then filter by calling ScoreOf that is O(1)
var filtered = ctx.Cache.GetMembersByTag("TAG 1")
	.Where(member => member.Key == "sorted set key" && member.MemberType == TagMemberType.SortedSetMember
			&& sortedSet.ScoreOf(member.GetMemberAs<string>()) <= 500);
```

**Comment by PrachiChoudhary** [comment]
Thanks for the help.
