### ISSUE TITLE
Work in ActionFilter.

### ISSUE THREAD

**Issue by minhncud** [thepirat000/CachingFramework.Redis#47]
Can i use CachingFramework.Redis to handle Redis's changing from ActionFilter like OnActionExecuting? 
I made a html Cache in server (like OutputCache in AspNet) instead of ResponseCache at OnActionExecuting. (the htmlCache stores on Redis)
I want to check keys on Redis before deciding use Cache or not.
I can do this manually but i don't know how to work best with CachingFramework.Redis.
* Example:
1.   Client sends a request to the server.
2.   Server checks a key names "IsChanged" on Redis
3a. If  "IsChanged" is "False" then get HtmlCache from Redis, send to clients.
3b. If "IsChanged" is "True" then go to Controller: get cache objects from Redis keys using CachingFramework.Redis. After that, create new "HtmlCache" key, set "IsChanged" to "False" on Redis (do it in OnResultExecuted) and send result to client.

Thank you.

**Comment by thepirat000** [comment]
I think I didn't fully understand your problem, could you elaborate a little bit more?

- What are the events that modifies the "IsChanged" value?
- What is your "HtmlCache"? a collection of cached objects retrieved and invalidated at once?

Anyway, I think your "IsChanged" value is actually to indicate that your "HtmlCache" is obsolete or has been invalidated.

So you don't really need a value for that, instead of changing the value to true, you could just invalidate (remove) the key that contains your "HtmlCache", and use a Fetch operation in order to get the data from the real source when there is a cache miss:

```c#
public HtmlCache GetHtmlCache()
{
  var htmlCache = _redisContext.Cache.FetchObject<HtmlCache>("key", () => GetFromOriginalSource());
  return htmlCache;
}

private HtmlCache GetFromOriginalSource()
{
  // ...get the value from database
  return new HtmlCache();	
}

public void Invalidate()
{
  _redisContext.Cache.Remove("key");
}
```

**Comment by minhncud** [comment]
Thank you very much, I can explain it deeply: 
- First, i work with MVC environtment. I try to do as this plan:
![redis diagram](https://user-images.githubusercontent.com/36953180/45019790-651f6600-b057-11e8-8bdd-cd717356eef3.png)
- But you're right, IsChanged is not necessary. 
- **HtmlCache** works like OutputCache but i store it on Redis instead of memory, **HtmlCache** has its duration and it contains the string which you can see in view (cshtml). So if i use Fetch in OnActionResult with a function to get data, create view by Stream, does it mean i don't need code anything inside Controller (except "return View();")?

**Comment by thepirat000** [comment]
I still don't understand your invalidation logic, but a minimal implementation of an output cache can be as follows:

```c#
public class HtmlCacheAttribute : ActionFilterAttribute
{
    public static RedisContext RedisContext { get; set; } = new RedisContext("localhost:6379");

    public override void OnActionExecuting(ActionExecutingContext context)
    {
        var key = GetCacheKeyForRequest(context.HttpContext);
        var cachedValue = RedisContext.Cache.GetObject<string>(key);
        if (cachedValue != null)
        {
            context.Result = new ContentResult() { Content = cachedValue };
            return;
        }

        // Swap in a new TextWriter so we can capture the output
        var cachingWriter = new StringWriter(CultureInfo.InvariantCulture);
        var originalWriter = context.HttpContext.Response.Output;
        context.HttpContext.Response.Output = cachingWriter;

        context.HttpContext.Items["cachingWriter"] = cachingWriter;
        context.HttpContext.Items["originalWriter"] = originalWriter;
    }

    public override void OnResultExecuted(ResultExecutedContext filterContext)
    {
        var originalWriter = filterContext.HttpContext.Items["originalWriter"] as TextWriter;
        if (originalWriter != null)
        {
            // Restore original writer
            filterContext.HttpContext.Response.Output = originalWriter;

            // Grab output and write it
            var cachingWriter = filterContext.HttpContext.Items["cachingWriter"] as StringWriter;
            var capturedText = cachingWriter.ToString();
            filterContext.HttpContext.Response.Write(capturedText);

            // Cache output
            var key = GetCacheKeyForRequest(filterContext.HttpContext);
            RedisContext.Cache.SetObject(key, capturedText);
        }
    }

    private string GetCacheKeyForRequest(HttpContextBase context)
    {
        return context.Request.Url.ToString();
    }
}
```

**Comment by minhncud** [comment]
My bad, i typed not clearly. I work in AspNet Core MVC, not AspNet MVC.  This is my invalidation logic:
* Client sends url request to front-end (FE) server:
**OnActionExecuting**: check Redis:
1. If "HtmlCache" key exists: 
- Send it to client 
2. If there is no "HtmlCache" key: 
(reason: **key expired** or **Another server changes data and remove "HtmlCache" key (like your hint)**
Inside **Controller**:
- FE server gets data from database, creates multiple objects, stores them on Redis (RealtimeData keys)
- FE server creates a View to send Html to client
**OnResultExecuted**: create OutputCache, stores on Redis (HtmlCache key)

As i said, i can create cache manually. This is my project build-in your CachingFramework.Redis master if you need: 
[http://www.mediafire.com/file/629vjp64ji2zcyg/OutputCaching.rar/file]
(customize from [https://zablo.net/blog/post/asp-net-core-redis-html-cache])

But i hope i can merge my cache with yours to build something work like that: 
![cache-object](https://user-images.githubusercontent.com/36953180/45071689-c3a11e80-b101-11e8-8c9b-ac67f870c1e7.png)

* Request comes:
- If **HtmlCache** exists and both object 1, object 2 does not change
=> Send directly HtmlCache to client

- If **HtmlCache** exists but **object 1** key is updated
=> Go to Controller, get the newest data of object 1, return View and set a copy of its to new **HtmlCache** key on Redis

- If (**HtmlCache** exists but **object 1** key is removed) OR (**HtmlCache** does not exists)
=> Go to Controller, use Fetch to get data from DB, set new **object 1** key, return View and set a copy of its to new **HtmlCache** key on Redis
_(same as **object 2**)_

**Comment by minhncud** [comment]
Maybe I misunderstand, we are working with 2 other ways. Thank you for spending time.
