### ISSUE TITLE
Work with data value in Redis key

### ISSUE THREAD

**Issue by minhncud** [thepirat000/CachingFramework.Redis#49]
I stored a list object (contains ID and values) to a key on Redis and i want to update it without remove that key and insert again. I need get a smaller list object, insert new object, remove last object or edit an object. 
1. If i store list object by Json string, maybe i need use EVAL with Lua script but i don't know about Lua 
2. If i store list object by Hash, i don't know how to **get range** in the Hash key. 
* Example of Hash:
     _  Store **list<string,string> Object** : 
{ (id1, value1), (id2, value2), (id3, value3), (id4, value4), (id5, value5), (id6, value6) }
     _  Need get **{ (id3, value3), (id4, value4) }** for object1
3. If i store list object by Sortset, how can i **update value** with a score (if i use score instead of field in Hash)? 

Can you help me that? Thanks.
_
Edit: I think Hash is the best choice, so can i get smaller list object instead of getting all and filter in server? Because i use GetHashedAll to get 60 fields in a key, it run in ~2s. Thank you.

**Comment by thepirat000** [comment]
I think this is a general redis data design question. And it really depends on how are you going to access data. i.e. if you always retrieve a small set of the hash keys, you probably don't need range queries, and can do it with multiple HGET or HMGET

**Comment by thepirat000** [comment]
Didn't wanted to close this yet, sorry. 

You should be able to get multiple hash fields with [RedisDcitionary collection](https://github.com/thepirat000/CachingFramework.Redis/blob/master/COLLECTIONS.md#redis-hashes--) `GetRange` method.

**Comment by minhncud** [comment]
Yeah, you've just inserted **GetRange**, right? Yesterday i don't see it in **RedisDictionary.cs**.
And is your new master project does not automatically get Nuget's packages? I can not build it to test :( 

- I tried manually to edit **RedisDictionary.cs**, **RedisCacheProvider.cs** but error shows in Array.Empty.

**Comment by thepirat000** [comment]
yes, I've added come missing methods.

Will check the build error

**Comment by minhncud** [comment]
Although i can not debug by add a new project which has dependencies base on your master projects. Errors about version of Newsonsoft.Json,  StackExchange.Redis. If i get them manually, new error **Could not load file or assembly "CachingFramework.Redis, Version=10.0.1.0, Culture=neutral, PublicKeyToken=3982df00cecbd320"** happened.
But using the newest version of CachingFramework.Redis in a single project solution, it works well, thank you very much :D 

Higher version (just idea): can we update a hashkey like this: "Adding a row in hash key and remove the first row, reducing another rows index by 1 to keep same row quantity" by a single method?
Example: Create a hash key:
- row1: key=1, value="value1"
- row2: key=2, value="value2"
- row3: key=3, value="value3"
After updated newest row, this key becomes:
- row1: key=1, value="value2"
- row2: key=2, value="value3"
- row3: key=3, value="value4"

**AddRange** and **GetRange** are only used when we know exactly key and value of each row. 

But if in a work group, the key is create by the admin with 50 rows (with 50 values), user1 adds a new row, user2 adds a new row,.... when I wants to show **50 newest values** , how do i do?. Can you make something like update with sorting by key/ index, then GetRangeFromTo?
