### ISSUE TITLE
Get data from a Hash key contains many small list object in a request to Redis

### ISSUE THREAD

**Issue by minhncud** [thepirat000/CachingFramework.Redis#50]
Me again, i'm sorry but i have a question.
Simple, we have **context.Collections.GetRedisDictionary<_type_, _T_>("_hashkey_")** to take a hashkey in Redis. 
But if i have a class:
**class MultiObject
{
 List<T1> list1 { get; set; }
 List<T2> list2 { get; set; }
 List<T3> list3 { get; set; }
}**

Can i get or set to a hashkey like that:
![hashkey](https://user-images.githubusercontent.com/36953180/45811770-2e547b80-bcf8-11e8-9298-238c8eb8f269.png)

It uses to store lists of multiple type objects which have 1~5 records each type.
Thank you.

**Comment by thepirat000** [comment]
Maybe I don't understand your question, but it looks like you need to store a JSON string on each hash field?

Nothing stops you to do that as long as your class is serializable/deseralizable under the [serialization method](https://github.com/thepirat000/CachingFramework.Redis#serialization) used.

The values are serialized when storing them on the Redis hash fields,

**Comment by minhncud** [comment]
This sample is easier to read
![cake](https://user-images.githubusercontent.com/36953180/45857230-04e03200-bd82-11e8-8ad8-a9ada4c8d370.png)
- If i only have first 3 fields, i can use **context.Collections.GetRedisDictionary<string, Fruit>("HashObjects")** to add or get values in Fruit object
- But in this photo, if i use **context.Collections.GetRedisDictionary<string, Fruit>("HashObjects")** to get Fruit values and **context.Collections.GetRedisDictionary<string, Cake>("HashObjects")** to get Cake values, it returns nothing. 
- I want to store both Fruit and Cake in Food like this:
![food](https://user-images.githubusercontent.com/36953180/45857391-a5365680-bd82-11e8-814b-385f70add47b.png)

- About serialization between Object and Json, do you mean using string as **context.Collections.GetRedisDictionary<string, string>("HashObjects")** ?
