### ISSUE TITLE
Remove an item from a list of geomembers

### ISSUE THREAD

**Issue by riccardobecker** [thepirat000/CachingFramework.Redis#51]
Hi, i created a list of geomembers containing lat/long and some Airport object as below. 

 list.Add(new GeoMember<Airport>(airport2.Latitude, airport2.Longitude, airport2));
 context.GeoSpatial.GeoAdd<Airport>(key, lists.ToArray());

This works fine and i can query it using GeoRadius.

Question: what would be the approach to remove a specific airport from the list in redis?

thanks in advance!

Riccardo

**Comment by thepirat000** [comment]
Hi

Geohashes are SortedSets actually, so you can remove it with [ZREM]() Redis command, or with the RemoveFromSortedSet method, like this:

```c#
context.Cache.RemoveFromSortedSet(key, airport2);
```

**Comment by riccardobecker** [comment]
Ah ok, meaning this where key is the id of the list and airport2 must be exact the same as the one in the list? Would be better to be able removebyid or something?

Thanks for your comments anyway.
