### ISSUE TITLE
Question: At what point is the database queried?

### ISSUE THREAD

**Issue by du8die** [thepirat000/CachingFramework.Redis#53]
I have a question regarding the internals of the library.

At what point is the database queried?

Given the following code:

`redisCtx.Collections.GetRedisList(Of student)("students:" & customer.id & ":" & school.id).Where(function(x) x.last_name = "test").FirstOrDefault()`

Is the entire list in this case brought over the wire and THEN filtered, or is the filtering done BEFORE being brought over the wire?

Thanks!

**Comment by thepirat000** [comment]
You can run a MONITOR on a redis-client and you will see the commands executed. In your particular case, the framework will traverse the list from its first element until the first element that matches your where clause... For example assuming the first element of the list has the last_name you asked for, when you execute the `FirstOrDefault()` you will see the following commands executed:

> [0 127.0.0.1:16307] "LLEN" "students:1:2"
> [0 127.0.0.1:16307] "LINDEX" "students:1:2" "0"

Check the Time Complexity description on the [LINDEX](https://redis.io/commands/lindex) command:

**Comment by thepirat000** [comment]
FYI

I realized that when iterating over the enumerator on the `RedisList`, the framework was checking the length of the list on each iteration which is sub-optimal. 

This was changed, and now the `GetEnumerator` implementation avoids the unnecessary calls to [LLEN](https://redis.io/commands/llen).

This was changed on version 10.0.3

**Comment by du8die** [comment]
> You can run a MONITOR on a redis-client and you will see the commands executed. In your particular case, the framework will traverse the list from its first element until the first element that matches your where clause... For example assuming the _second_ element of the list has the last_name you asked for, when you execute the `FirstOrDefault()` you will see the following commands executed:
> 
> > [0 127.0.0.1:16307] "LLEN" "students:1:2"
> > [0 127.0.0.1:16307] "LINDEX" "students:1:2" "0"
> > [0 127.0.0.1:16307] "LINDEX" "students:1:2" "1"
> 
> Check the Time Complexity description on the [LINDEX](https://redis.io/commands/lindex) command:

Thank you for the quick reply. I'm a relative noob to Redis - so I'll do some reading and figure this out. 

By the way - I did update to 10.0.3 - and it still looks like LLEN is being called on every iteration...

![redis](https://user-images.githubusercontent.com/4031879/48975428-2cc76c80-f035-11e8-9983-8b4bd5950099.png)

Thanks again!

**Comment by du8die** [comment]
Here's the code. 
```
Dim tmpStudents As IRedisList(Of student) = redisCtx.Collections.GetRedisList(Of student)("students:" & customer_id & ":" & school_id)
return tmpStudents.Where(Function(x) userStudents.Contains(x.id)).ToList
```

Sending you an email about the purpose... Don't want to clog up this thread with my inexperienced Redis drivel.

Thanks!

**Comment by thepirat000** [comment]
Are you sure you are pointing to the last version? I tried your code and the LLEN was called only once. I'm assuming the `userStudents` is an array of ints.

**Comment by thepirat000** [comment]
Closing this for now. If you're still having problems please reply to this
