### ISSUE TITLE
[Request] Add page size support for scan operations

### ISSUE THREAD

**Issue by CDargis** [thepirat000/CachingFramework.Redis#54]
It would be nice to be able to specify the page size when scanning keys or hashes. The default implementation will use a size of 10:

https://github.com/thepirat000/CachingFramework.Redis/blob/master/src/CachingFramework.Redis/RedisObjects/RedisDictionary.cs#L292

https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/RedisDatabase.cs#L415

https://github.com/StackExchange/StackExchange.Redis/blob/ec5ba30955abd5bfc0a79bcc51e0da1f7986f884/src/StackExchange.Redis/RedisBase.cs#L118

**Comment by thepirat000** [comment]
This was added on version 10.0.4, now you can specify the page size, for example, when you get a redis dictionary instance:

```
redisContext.Collections.GetRedisDictionary<string, string>(key, 50);
```

**Comment by CDargis** [comment]
Oh I missed that. And now I see it was also added to `ScanHashed()`.  Awesome thank you!

**Comment by thepirat000** [comment]
you didn't missed it, it was added upon your request 👍

**Comment by CDargis** [comment]
That was fast!
