### ISSUE TITLE
Question on long lived RedisContext documentation

### ISSUE THREAD

**Issue by CDargis** [thepirat000/CachingFramework.Redis#55]
Hi there. Not an issue just a question. The [documentation here](https://github.com/thepirat000/CachingFramework.Redis) reads 

> The RedisContext object should be shared and reused between callers. It is not recommended to create a RedisContext per operation. Please check StackExchange.Redis documentation for more information.

Is it the _RedisContext_ object that must be long-lived or the _IConnectionMultiplexer_ ? Meaning if my multiplexer is long-lived and I am `new`ing up `RedisContext` objects and injecting in the multiplexer, there is no concern there? Asking because I'll be using `CachingFramework.Redis` alongside another (separate) framework that requires a `StackExchange.Redis.IConnectionMultiplexer`. I'd like both frameworks to use the same pool of multiplexers.

Thanks.

**Comment by thepirat000** [comment]
It is the `IConnectionMultiplexer` which should be long-lived. The `RedisContext` object holds a reference to the connection multiplexer. So I think you are doing fine, as long as the multiplexer you are injecting is long-lived.

Another option would be to maintain just a static `RedisContext` object and when you need the `IConnectionMultiplexer` you can call `redisContext.GetConnectionMultiplexer()`

**Comment by CDargis** [comment]
Thanks!
