### ISSUE TITLE
Access to ConnectionMultiplexer on IContext interface

### ISSUE THREAD

**Issue by larsbaunwall** [thepirat000/CachingFramework.Redis#56]
I'm using DI in my solution, where I'm injecting `IContext` instead of the `RedisContext` class.

In some of my code, I'm using `RedisContext.GetConnectionMultiplexer()` for some of the low-level Redis-stuff, but that is not exposed on any interface, thus I need concrete knowledge of the `RedisContext`class, which breaks mocking in my tests.

Could we expose `RedisContext.GetConnectionMultiplexer()`on the `IContext`interface also?

**Comment by thepirat000** [comment]
Included on version 10.0.5, please upgrade your references
