### ISSUE TITLE
Serialized Hash fields

### ISSUE THREAD

**Issue by christophe** [thepirat000/CachingFramework.Redis#59]
Hi there. I noticed an inconsistency between the different the different `RedisCacheProvider.SetHashedAsync()` methods. In all but one (`public async Task SetHashedAsync<T>(string key, string field, T value, ...)`, line 1497), `field` is serialized. When `field` is a string, you end up with "duplicate" keys, one raw, the other the same but surrounded with quotes by `JsonSerializer`.

Cheers and thanks!

**Comment by thepirat000** [comment]
The behavior is that the methods that accepts the `field` as a `string` will not be serialized. And the methods with generic type `TK` for the `field`, will serialize the field regardless of its type.

Could you share an example that generates duplicate keys?

**Comment by christophe** [comment]
Yes, I prepared a simplified test scenario:

```
var item = new MyItem { Id = "test" };
var items = new List<MyItem> { item };

await _redis.Cache.SetHashedAsync("cache-test", item.Id, item);
await _redis.Cache.SetHashedAsync<string, MyItem>("cache-test", items.ToDictionary(i => i.Id, i => i));
```

I would expect both calls to produce the same result, but instead I get this:

![image](https://user-images.githubusercontent.com/6014202/68400921-21534f80-0179-11ea-80fb-a95665abce6d.png)

**Comment by thepirat000** [comment]
You should be consistent in using always the overloads without (or without) the generic field type.

This should work as expected (using the non-generic overloads);

```c#
await _redis.Cache.SetHashedAsync("cache-test", item.Id, item);
await _redis.Cache.SetHashedAsync("cache-test", items.ToDictionary(i => i.Id, i => i));
```

Or using the generic overloads (this will trigger the serialization on the field):

```
await _redis.Cache.SetHashedAsync<string, MyItem>("cache-test", item.Id, item);
await _redis.Cache.SetHashedAsync<string, MyItem>("cache-test", items.ToDictionary(i => i.Id, i => i));
```

**Comment by christophe** [comment]
You're right. I'm sorry, I didn't even notice these overloads.

Thank you very much for your assistance!
