### ISSUE TITLE
Need ability to pass command flags on get operations

### ISSUE THREAD

**Issue by ssmillard** [thepirat000/CachingFramework.Redis#61]
Need to pass command flags when calling get operations.  Our implementation has 3 nodes, 1 primary and 2 slaves.  All operations are defaulting to PreferMaster.  In order to utilize slaves for read operations, StackEchange.Redis requires the CommandFlag.PreferSlave on read operations.

https://github.com/StackExchange/StackExchange.Redis/blob/master/src/StackExchange.Redis/Enums/CommandFlags.cs

**Comment by thepirat000** [comment]
This was added on version 11.1.0, please upgrade and re-test.

Added flags parameter to almost all `RedisCacheProvider` methods

**Comment by ssmillard** [comment]
Works great.  Thanks
