### ISSUE TITLE
What is proper way to dispose Redis Connection.

### ISSUE THREAD

**Issue by maheshdwaghmare** [thepirat000/CachingFramework.Redis#62]
We have used AWS Redis Cache `Family redis5.0` in our Application having `.Net Framework 4.6.1`.

Initially, Everything was working fine. Since last couple of weeks, we are facing exception : 
> No connection is available to service this operation: GET xxxxx; SocketClosed on xxxxx/Interactive".

Then, we analyse our connections are not getting closed as we have not disposed Redis connections. Also, we found that there are plenty of old connections are there in Redis Cache.
Thus, we set AWS Redis timeout parameter from 0 to 20 so that connection will automatically get closed after 20 seconds if it is idle.

After this change, we are getting frequency of above mentioned exception is getting increased.
Then we have analyzed after every 20 seconds, connections were getting closed which is expected. So, When they were closed, `IsConnecting` property of `ConnectionMultiplexer` is true. But, our Redis context still exists. If our code triggers any Redis operation at that instant, then we get exception :

> "No connection is available to service this operation: GET xxxxx; SocketClosed on xxxxx/Interactive".
					
So, to avoid that before every Redis operation , we place check for `IsConnecting` and `IsConnected` Properties like below.
					
    public T Get<T>(string redisKey)
    {
        StringBuilder logString = new StringBuilder();
        while(_context.GetConnectionMultiplexer().IsConnecting)
        {

        }
        if (_context.GetConnectionMultiplexer().IsConnected)
            return _context.Cache.GetObject<T>(redisKey);
        else
            return default(T);
    }
					
We are not like this fix as it can be run for infinite loop.
					
Then, we realize rather than setting timeout to 20 seconds and checking connection before each Redis operation, we should set timeout to 0 seconds and dispose the connections.
So, at the end of all Redis operations, we called dispose of Redis context. But, In that case Redis context is still there and it is not allowing us to reinitialize it.

Please What and when the proper way to dispose Redis connections? Thanks in advance.

**Comment by thepirat000** [comment]
You should not dispose the connection multiplexer, check [this](https://stackexchange.github.io/StackExchange.Redis/Basics.html)
