### ISSUE TITLE
create tryget async method

### ISSUE THREAD

**Issue by ssmillard** [thepirat000/CachingFramework.Redis#63]
Would it be possible to create a async  try get method? Such as:
		public async Task<(bool HasValue, T result)> TryGetValueAsync<T>(string key, CommandFlags flags = CommandFlags.None)
        {
           var cacheValue = await RedisConnection.GetDatabase().StringGetAsync(key, flags).ForAwait();
           
 if (!cacheValue.HasValue)
            {
                return (false, default(T));
            }
            value = Serializer.Deserialize<T>(cacheValue);
            return (true,value);
        }

Thanks

**Comment by thepirat000** [comment]
I don't like using tuples so much, maybe it should return an instance of a class with the boolean and object

**Comment by ssmillard** [comment]
That would also work.  I was just trying to make it as small as a change as possible.

**Comment by thepirat000** [comment]
The method `TryGetValueAsync` was added on version 11.1.1, please upgrade your references and re-test.

**Comment by ssmillard** [comment]
I was looking for the change in the  ICacheProviderAsync interface. It looks like the change was completed on  IRedisDictionaryAsync.  I missed that in you initial response about the tuple,  you reference the dictionary as instead of the string that I opened this request.  Is it possible to create the tryAsync on the string value?
