### ISSUE TITLE
System.Text.Json(STJ) Serializer Support

### ISSUE THREAD

**Issue by louisfischer** [thepirat000/CachingFramework.Redis#65]
Any plans to support the new System.Text.Json (SWT) as a serializer option?

**Comment by thepirat000** [comment]
This was added on commit https://github.com/thepirat000/CachingFramework.Redis/commit/1f46113793860b808b69d9221cc490ebbbd966b2

Now the default for .NET Core is System.Text.Json serializer. But if you still want to use Newtonsoft.Json, you can import the new package [`CachingFramework.Redis.NewtonsoftJson`](https://www.nuget.org/packages/CachingFramework.Redis.NewtonsoftJson/)

This was released on version 12.0.0
