### ISSUE TITLE
Add a  Method AddRange with additional parameter Tags to RedisDictionary 

### ISSUE THREAD

**Issue by saarfa** [thepirat000/CachingFramework.Redis#66]
I use Redis on top of SQLSever, every table has a corresponding hash.
I use Tags as foreign keys to create tables relations.
In order To support bulk insert of rows having the same parent table relation i need
void AddRange(IEnumerable<KeyValuePair<TK, TV>> items, string[] tags);
in  RedisDictionary.
Doe's creating one will be incompatible with a cluster topology.

**Comment by thepirat000** [comment]
Method `void AddRange(IEnumerable<KeyValuePair<TK, TV>> collection, string[] tags);` was added to the `RedisDictionary` (also an Async version) on version 12.0.2

Please upgrade your references to the latest and re-test
