### ISSUE TITLE
Dispose and Close

### ISSUE THREAD

**Issue by verysimplenick** [thepirat000/CachingFramework.Redis#7]
Hi. I want try your code, but I don't see IDisposable at your Context(). For now I can't use using for my code, and need run GetConnectionMultiplexer().Dispose() in each catch block for example. ( I think if ConnectionMultiplexer implement IDisposable you MUST implement same, because StackExchange can reimplement they Dispose (for now it's only run Close AFAIK). BTW how closing connection (if u don't wanna implement IDisposable) must showed in docs. 
ps any way thanks for your code and work. give you a star, but you need implement IDisposable  :+1:

**Comment by thepirat000** [comment]
Thanks for your comments. Will take a look.

**Comment by thepirat000** [comment]
Just implemented IDisposable on the context. 
This is on version 4.9.0

Thanks!
