### ISSUE TITLE
Add Async Support

### ISSUE THREAD

**Issue by alanspires** [thepirat000/CachingFramework.Redis#8]
Example. 

``
await context.Cache.FetchObjectAsync<T>(key, async () => await GetObjectAsync(1));
``

So overloads including 

``
System.Func<Task<T>> 
``
Thanks!

**Comment by thepirat000** [comment]
Will try to get some time to work on the async API. Thanks.

**Comment by thepirat000** [comment]
I've just added the async API to the RedisCacheProvider. You should be able to do what you want now.
Regards.

**Comment by alanspires** [comment]
Thank you!
