### ISSUE TITLE
Nuget package is unoptimized

### ISSUE THREAD

**Issue by ovska** [thepirat000/CachingFramework.Redis#82]
The `CachingFramework.Redis 14.1.0`-package is unoptimized, as reported by [UnoptimizedAssemblyDetector](https://www.nuget.org/packages/UnoptimizedAssemblyDetector):

> UnoptimizedAssemblyDetector.targets(14, 5): Unoptimized assembly detected: 'CachingFramework.Redis.dll' at /home/xxx/.nuget/packages/cachingframework.redis/14.1.0/lib/net6.0/CachingFramework.Redis.dll

Release-configuration should probably be used in `dotnet pack`-commands in `pack.cmd`. [The default is Debug](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack#options:~:text=The%20default%20for%20most%20projects%20is%20Debug).

**Comment by thepirat000** [comment]
Fixed starting on version 15.0.0, please upgrade your references and re-test

**Comment by ovska** [comment]
Thanks for the quick response, from a happy user of your library :)
