### ISSUE TITLE
No code for 15 release

### ISSUE THREAD

**Issue by GraySerg** [thepirat000/CachingFramework.Redis#83]
Hi. I have found a 15 release, but no source code. Are you repository was hijacked?

**Comment by thepirat000** [comment]
do you mean there is no 15.0.0 tag in the source code?
I just forgot to push the tag, now the code is tagged for version 15.0.0

**Comment by GraySerg** [comment]
No, i mean no source code changes in repository. Last changes was made 05.08.2022. And, by the way, you can safely remove MsgPack.Cli from the references and bump StackExchange.Redis to the latest version

**Comment by ovska** [comment]
I think there were only build changes for 15.0.0, not code changes. See: #82

**Comment by thepirat000** [comment]
Oh, I see... 

I forgot to push the latest commit, the repository was outdated. I've fixed it already.

**Comment by thepirat000** [comment]
> No, i mean no source code changes in repository. Last changes was made 05.08.2022. And, by the way, you can safely remove MsgPack.Cli from the references and bump StackExchange.Redis to the latest version

Do you mean for `CachingFramework.Redis.MsgPack` package, right?
