### ISSUE TITLE
BinarySerializer isn't available on .NET 6.0

### ISSUE THREAD

**Issue by du8die** [thepirat000/CachingFramework.Redis#86]
I'm trying to get the framework running on a .NET 6.0 project.

RedisContext.DefaultSerializer = new BinarySerializer(); leads to a "The type or namespace name 'BinarySerializer' does not exist in the namespace 'CachingFramework.Redis.Serializers' (are you missing an assembly reference?)"

When I use intellisense, the Serializers object has RawSerializer and JsonSerializer.

Any idea what I'm doing wrong?

Thanks,

**Comment by thepirat000** [comment]
As far as I know there is no BinarySerializer in .NET Core.

https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/binaryformatter-serialization-obsolete

This library only support binary serialization for the .NET Framework

**Comment by du8die** [comment]
Thanks. Will switch to JSON.
