### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [thepirat000/CachingFramework.Redis#87]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by thepirat000** [comment]
Hi

I don't think this is the right place to discuss or compare Redis / Kafka / RabbitMQ, sorry.

Check this for example: https://payodatechnologyinc.medium.com/rabbitmq-kafka-and-redis-which-broker-to-choose-for-a-microservice-554eeb47af68#:~:text=Use%20case%3A,RabbitMQ%20will%20do%20its%20job.

Note this library is just about Redis
