### ISSUE TITLE
Can't Get Geo to Work

### ISSUE THREAD

**Issue by alanspires** [thepirat000/CachingFramework.Redis#9]
I keep getting this error.

ERR Error running script (call to f_95f42165ca0309461e16d29f5efa546545d10a83): @user_script:1: @user_script: 1: Unknown Redis command called from Lua script 

I am using a AWS ElastiCache Redis 2.8.24.

Set Command
``
Context.GeoSpatial.GeoAdd(cacheKey, new GeoCoordinate(pe.Latitude.Value, pe.Longitude.Value), pe)
``

Get Command
``
Context.GeoSpatial.GeoRadius<ProfileEvent>(cacheKey, new GeoCoordinate(34, -104), 500, Unit.Miles)
``

Any Ideas?

**Comment by alanspires** [comment]
Is this because it requires Redis >= 3.2.0? If so might be a good idea to update the Readme, cheers!

**Comment by thepirat000** [comment]
That's correct, it requires redis >= 3.2.0
I've just update the readme.
Thanks for your suggestions!
